/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as OrdersRouteImport } from './routes/orders'
import { Route as OrderRouteImport } from './routes/order'
import { Route as FiltersRouteImport } from './routes/filters'
import { Route as CreateProductRouteImport } from './routes/create-product'
import { Route as ProductIdRouteImport } from './routes/$productId'
import { Route as IndexRouteImport } from './routes/index'
import { Route as CategoryCategoryIdRouteImport } from './routes/category.$categoryId'

const OrdersRoute = OrdersRouteImport.update({
  id: '/orders',
  path: '/orders',
  getParentRoute: () => rootRouteImport,
} as any)
const OrderRoute = OrderRouteImport.update({
  id: '/order',
  path: '/order',
  getParentRoute: () => rootRouteImport,
} as any)
const FiltersRoute = FiltersRouteImport.update({
  id: '/filters',
  path: '/filters',
  getParentRoute: () => rootRouteImport,
} as any)
const CreateProductRoute = CreateProductRouteImport.update({
  id: '/create-product',
  path: '/create-product',
  getParentRoute: () => rootRouteImport,
} as any)
const ProductIdRoute = ProductIdRouteImport.update({
  id: '/$productId',
  path: '/$productId',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const CategoryCategoryIdRoute = CategoryCategoryIdRouteImport.update({
  id: '/category/$categoryId',
  path: '/category/$categoryId',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/$productId': typeof ProductIdRoute
  '/create-product': typeof CreateProductRoute
  '/filters': typeof FiltersRoute
  '/order': typeof OrderRoute
  '/orders': typeof OrdersRoute
  '/category/$categoryId': typeof CategoryCategoryIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/$productId': typeof ProductIdRoute
  '/create-product': typeof CreateProductRoute
  '/filters': typeof FiltersRoute
  '/order': typeof OrderRoute
  '/orders': typeof OrdersRoute
  '/category/$categoryId': typeof CategoryCategoryIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/$productId': typeof ProductIdRoute
  '/create-product': typeof CreateProductRoute
  '/filters': typeof FiltersRoute
  '/order': typeof OrderRoute
  '/orders': typeof OrdersRoute
  '/category/$categoryId': typeof CategoryCategoryIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/$productId'
    | '/create-product'
    | '/filters'
    | '/order'
    | '/orders'
    | '/category/$categoryId'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/$productId'
    | '/create-product'
    | '/filters'
    | '/order'
    | '/orders'
    | '/category/$categoryId'
  id:
    | '__root__'
    | '/'
    | '/$productId'
    | '/create-product'
    | '/filters'
    | '/order'
    | '/orders'
    | '/category/$categoryId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ProductIdRoute: typeof ProductIdRoute
  CreateProductRoute: typeof CreateProductRoute
  FiltersRoute: typeof FiltersRoute
  OrderRoute: typeof OrderRoute
  OrdersRoute: typeof OrdersRoute
  CategoryCategoryIdRoute: typeof CategoryCategoryIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/orders': {
      id: '/orders'
      path: '/orders'
      fullPath: '/orders'
      preLoaderRoute: typeof OrdersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/order': {
      id: '/order'
      path: '/order'
      fullPath: '/order'
      preLoaderRoute: typeof OrderRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/filters': {
      id: '/filters'
      path: '/filters'
      fullPath: '/filters'
      preLoaderRoute: typeof FiltersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/create-product': {
      id: '/create-product'
      path: '/create-product'
      fullPath: '/create-product'
      preLoaderRoute: typeof CreateProductRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/$productId': {
      id: '/$productId'
      path: '/$productId'
      fullPath: '/$productId'
      preLoaderRoute: typeof ProductIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/category/$categoryId': {
      id: '/category/$categoryId'
      path: '/category/$categoryId'
      fullPath: '/category/$categoryId'
      preLoaderRoute: typeof CategoryCategoryIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ProductIdRoute: ProductIdRoute,
  CreateProductRoute: CreateProductRoute,
  FiltersRoute: FiltersRoute,
  OrderRoute: OrderRoute,
  OrdersRoute: OrdersRoute,
  CategoryCategoryIdRoute: CategoryCategoryIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
